import type { Metadata } from "next";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Provider from "@/providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
